### ISSUE TITLE
Figure out if/how to apply versioning to the Notify Protocol

### ISSUE THREAD

**Issue by paulwalk** [coar-notify/coar-notify.net#15]
It's not clear where this would be applied, since the underlying standards have their own versioning. Possibilities:

1. versioning the `@context` - but this has not changed so far
2. version the vocabulary - should this be separately versioned?

**Comment by paulwalk** [comment]
This is now a more pressing issue, because we want to add a new pattern for un-processable notifications which will need a new "Type" (vocabulary term)

**Comment by paulwalk** [comment]
We are now looking at the possibility of using JSON Schema for the patterns, and then versioning the schema(s).

**Comment by steph-ieffam** [comment]
Please @paulwalk take a look at this issue https://github.com/coar-notify/notify.coar-repositories.org/issues/25. This is related to introducing version in Notify

**Comment by paulwalk** [comment]
Hi @steph-ieffam - the Editorial Board is actively discussing this now.

**Comment by paulwalk** [comment]
This is now fixed in the `development` branch

**Comment by paulwalk** [comment]
Now deployed into production at https://coar-notify.net
