### ISSUE TITLE
Accept notification does not specify `object` in docs or example, but `object` is a required field

### ISSUE THREAD

**Issue by richard-jones** [coar-notify/coar-notify.net#27]
Reviewing the Accept notification here 

https://notify.coar-repositories.org/specification/patterns/accept/

The `object` property is not listed on the left, or provided in the example, but the base specification says that an `object` field must be included

https://notify.coar-repositories.org/specification/patterns/

**Comment by paulwalk** [comment]
This is now fixed in the `development` branch

**Comment by paulwalk** [comment]
Now deployed into production at https://coar-notify.net

**Comment by paulwalk** [comment]
Now deployed into production at https://coar-notify.net
