### ISSUE TITLE
Uncertainty as to the "required" status of some top-level fields

### ISSUE THREAD

**Issue by richard-jones** [coar-notify/coar-notify.net#29]
The Core Payload documentation identifies 4 fields which are optional:

* actor
* inReplyTo
* context
* summary

In some subsequent notifications these fields are used, but I am unclear as to whether they are required or not.  It would be useful to have some of the traditional spec terminology (MUST, MUST NOT, SHOULD, etc) to clearly tell when a field is necessary or not.

It also seems likely that inReplyTo, for example, may be required in some specific notifications, and still optional in others, even when it is mentioned in the example, so it's difficult to make a judgement call.

**Comment by paulwalk** [comment]
This is now fixed in the `development` branch

**Comment by paulwalk** [comment]
Now deployed into production at https://coar-notify.net
