### ISSUE TITLE
"Required" status of sub fields in `object` and `context` fields

### ISSUE THREAD

**Issue by richard-jones** [coar-notify/coar-notify.net#30]
The notification examples show various usages of `object` and `context`, and it would be useful to know which fields are required and which are not.

All appearances of `object` and `context` contain an `id` and a `type`, so it seems likely they are required.  There are also fields which don't appear everywhere, but when they do are there any stipulated requirements for their content?

All appearances of `context` contain `ietf:cite-as`, so can we read that as required? Noting also that this always contains an `item`, and it would be useful to know the required properties of that.

It would be useful to introduce some of the MUST, MUST NOT, MAY, etc terminology to aid comprehension

**Comment by paulwalk** [comment]
This is now fixed in the `development` branch

**Comment by paulwalk** [comment]
Now deployed into production at https://coar-notify.net
