### ISSUE TITLE
Typing of the `target` in Accept example (and others)

### ISSUE THREAD

**Issue by richard-jones** [coar-notify/coar-notify.net#32]
From https://notify.coar-repositories.org/specification/patterns/accept/ under `target`

> A type which should include the value Service from AS 2.0.

The example provided gives the value `Organization`, and does not include `Service`.

`target.type` in the example should be `["Organisation", "Service"]`

Also affects:
* Reject https://notify.coar-repositories.org/specification/patterns/reject/

**Comment by paulwalk** [comment]
This is now fixed in the `development` branch
