### ISSUE TITLE
Worked examples for workflows would be valuable

### ISSUE THREAD

**Issue by richard-jones** [coar-notify/coar-notify.net#34]
In developing the integration for Invenio/Zenodo and PCI, there was some discussion and uncertainty in the development team as to what exactly would be in the notifications, and their meanings.

It would be really valuable if the workflow documentation included not only the generic forms of the notifications, but also worked examples of realistic notifications with documentation.

For example, in the PCI case of AnnounceReview, the `object` in the record cannot contain an identifier to the individual review on PCI, as these reviews don't have public identifiers, they instead sit on the "Recommendation" page (which has its own DOI), so what would the identifier in AccounceReview `object.id` be?

**Comment by paulwalk** [comment]
Ideally, the URLs in the payloads would actually point to something real (e.g. on the PCI site).

Failing that, the URLs should be described in the documentation in some detail, explaining what they actually point to

**Comment by paulwalk** [comment]
Regarding:

> For example, in the PCI case of AnnounceReview, the object in the record cannot contain an identifier to the individual review on PCI, as these reviews don't have public identifiers, they instead sit on the "Recommendation" page (which has its own DOI), so what would the identifier in AccounceReview object.id be?

I'm advised by PCI that the `id` for the `object` in *AccounceReview* is reliably the URL to the endorsement page + a target on that page.

A real example:
https://evolbiol.peercommunityin.org/articles/rec?articleId=794#review-3136

**Comment by paulwalk** [comment]
There is a worked example of the PCI workflow on the demo site here:

https://notify.antleaf.com/catalogue/workflows/repository-pci/

**Comment by paulwalk** [comment]
Now deployed into production at https://coar-notify.net
